/*
 * ViewSourcePanel.java
 *
 * Created on October 28, 2006, 12:14 PM
 */

package com.runstate.augur.ui.compose;

import com.runstate.augur.gallery.Msg;
import com.runstate.augur.ui.augurpanel.AugurPanel;

/**
 *
 * @author  dj
 */
public class ViewSourcePanel extends AugurPanel {
    
    Msg msg;
    
    /** Creates new form ViewSourcePanel */
    public ViewSourcePanel(Msg msg) {
        this.msg=msg;
        initComponents();
        msgText.setText(msg.getText());
        msgHeader.setText(msg.getBundleName()+":"+msg.getKnotId());
    }
    
    public String getTitle()
    {
        return "Source View of "+msg.getBundleName()+":"+msg.getKnotId();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        msgText = new javax.swing.JTextPane();
        msgHeader = new javax.swing.JLabel();

        msgText.setEditable(false);
        jScrollPane1.setViewportView(msgText);

        msgHeader.setText("Message id");
        msgHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(msgHeader, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(msgHeader)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msgHeader;
    private javax.swing.JTextPane msgText;
    // End of variables declaration//GEN-END:variables
    
}
