/*
 * SearchNavigator.java
 *
 * Created on October 10, 2006, 1:01 PM
 */

package com.runstate.augur.ui.viewer.navigators;

import com.runstate.augur.controller.Controller;
import com.runstate.augur.gallery.Bundle;
import com.runstate.augur.gallery.Msg;
import com.runstate.augur.gallery.models.BundleTreeModel;
import com.runstate.augur.gallery.models.BundleTreeNode;
import com.runstate.augur.ui.trees.PathRenderer;
import com.runstate.augur.ui.viewer.BrowserCommandHandler;
import com.runstate.augur.ui.viewer.views.SearchView;
import java.util.ArrayList;
import javax.swing.plaf.TreeUI;
import javax.swing.plaf.basic.BasicTreeUI;
import javax.swing.tree.TreePath;

/**
 *
 * @author  dj
 */
public class SearchNavigator extends AbstractNavigator {
    
    /** Creates new form SearchNavigator */
    public SearchNavigator(BrowserCommandHandler vch) {
        super(vch);
        initComponents();
        bundleTree.setModel(new BundleTreeModel(Controller.getGallery().getBundleManager()));
        bundleTree.setCellRenderer(new PathRenderer(false,false));
        TreeUI tui=bundleTree.getUI();
        if(tui instanceof BasicTreeUI) {
            BasicTreeUI ui=(BasicTreeUI)tui;
            ui.setExpandedIcon( null );
            ui.setCollapsedIcon( null );
            ui.setRightChildIndent(4);
            ui.setLeftChildIndent(4);
            putClientProperty("JTree.lineStyle","None");
        } else {
            System.out.println("Unable to assert icon styles on tree");
        }
        bundleTree.setSelectionRow(0);
    }
    
    public String getNavPanelName() { return "Search"; }
    
    public void focusOnMe() {
        requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bundleTree = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentPathLabel = new javax.swing.JLabel();

        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        bundleTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                bundleTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(bundleTree);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setText("No options available");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jLabel1.setText("Search for");

        jLabel2.setText("In");

        currentPathLabel.setText("/");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addContainerGap(163, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(searchText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(currentPathLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(searchButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(1, 1, 1)
                .add(searchText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(currentPathLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 371, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(searchButton))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        doSearch();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        doSearch();
    }//GEN-LAST:event_searchTextActionPerformed

    private void bundleTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_bundleTreeValueChanged
        TreePath[] selected=bundleTree.getSelectionPaths();
        if(selected==null) return;
        if(selected.length==1)
        {
            BundleTreeNode btn=(BundleTreeNode)selected[0].getLastPathComponent();
            String bundleName=btn.getFullPath();
            currentPathLabel.setText(bundleName);
        }
        else {
             currentPathLabel.setText("multiple");
        }
   
    }//GEN-LAST:event_bundleTreeValueChanged

    private void doSearch()
    {
        searchButton.setEnabled(false);
        searchText.setEnabled(false);
        bundleTree.setEnabled(false);
        TreePath[] selected=bundleTree.getSelectionPaths();
        if(selected==null) return;
        sv.clearView();
        for(TreePath t:selected) {
            BundleTreeNode btn=(BundleTreeNode)t.getLastPathComponent();

            Bundle bundle=btn.getBundle();
            ArrayList<Msg> results=bundle.search(searchText.getText());
            sv.addMsgs(results);
        }
        sv.expandRoot();
        searchButton.setEnabled(true);
        searchText.setEnabled(true);
        bundleTree.setEnabled(true);
    }

    private SearchView sv;
    
    public void setView(SearchView sv) {
        this.sv=sv;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree bundleTree;
    private javax.swing.JLabel currentPathLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchText;
    // End of variables declaration//GEN-END:variables
    
}
