/*
 * CixDoor2UI.java
 *
 * Created on October 7, 2006, 4:45 PM
 */

package com.runstate.augur.cix.ui;

import com.runstate.augur.controller.DoorEvent;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author  dj
 */
public class CixDoorUIPanel extends javax.swing.JPanel {
    
    /** Creates new form CixDoor2UI */
    public CixDoorUIPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("Sync Now");

        jScrollPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cix Connection Log", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        logTextArea.setColumns(20);
        logTextArea.setEditable(false);
        logTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        logTextArea.setRows(5);
        logTextArea.setBorder(null);
        jScrollPane1.setViewportView(logTextArea);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jButton2.setText("Clear Log");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(539, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(jButton2)
                .addContainerGap())
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        logTextArea.setText(sdf.format(new Date())+"-Log Cleared ");
         logTextArea.setCaretPosition(logTextArea.getText().length());
    }//GEN-LAST:event_jButton2ActionPerformed

    SimpleDateFormat sdf=new SimpleDateFormat("HH:mm:ss");
    
    void log(DoorEvent de) {
        String ti=sdf.format(de.getDate());
        logTextArea.setText(logTextArea.getText()+"\n"+ti+"-"+de.getMsg());
        logTextArea.setCaretPosition(logTextArea.getText().length());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logTextArea;
    // End of variables declaration//GEN-END:variables
    
}
