/*
 * SearchView.java
 *
 * Created on October 10, 2006, 3:20 PM
 */

package com.runstate.augur.ui.viewer.views;

import com.runstate.augur.gallery.Msg;
import com.runstate.augur.ui.viewer.BrowserCommandHandler;
import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author  dj
 */
public class SearchView extends AbstractViewPanel {
    
    /** Creates new form SearchView */
    public SearchView(BrowserCommandHandler vch) {
        super(vch);
        initComponents();
        clearView();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        msgDisplay = new javax.swing.JTextPane();

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);
        resultsTree.setCellRenderer(new MsgTreeCellRenderer());
        resultsTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                resultsTreeValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(resultsTree);

        jSplitPane1.setTopComponent(jScrollPane1);

        jScrollPane2.setViewportView(msgDisplay);

        jSplitPane1.setRightComponent(jScrollPane2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void resultsTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_resultsTreeValueChanged
        TreePath tp=resultsTree.getSelectionPath();
        
        if(tp==null) {
            msgDisplay.setText("");
        } else {
            DefaultMutableTreeNode dmtn=(DefaultMutableTreeNode)tp.getLastPathComponent();
            if(dmtn.getUserObject() instanceof String) {
                msgDisplay.setText("");
            } else {
                Msg msg=(Msg)dmtn.getUserObject();
                msgDisplay.setText(msg.getText());
            }
        }
    }//GEN-LAST:event_resultsTreeValueChanged
    
    public void clearView()
    {
        DefaultMutableTreeNode root=new DefaultMutableTreeNode("Search Results");
        root.setAllowsChildren(true);
        resultsTree.setModel(new DefaultTreeModel(root));
        resultsTree.expandRow(0);
    }
    
    
    public void addMsgs(ArrayList<Msg> results) {
        DefaultTreeModel dtm=(DefaultTreeModel)resultsTree.getModel();
        DefaultMutableTreeNode dtn=(DefaultMutableTreeNode)dtm.getRoot();
        for(Msg m:results) {
            DefaultMutableTreeNode dmtn=new DefaultMutableTreeNode(m);
            dtn.insert(dmtn,dtn.getChildCount());
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextPane msgDisplay;
    private javax.swing.JTree resultsTree;
    // End of variables declaration//GEN-END:variables
    
}
